# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0397816a71b36aaa5e658260efeb21fecac622cac3cc3c6801f538c84d5519b99f172e207df3975abed08b653a6473f03415a40be56965dc06ec262d61d91490

test:
  secret_key_base: cf041d399682adc42cbe2d4b6a8137b34030f1bdd1250a1ec1c0f2055c344fc936ce9143ca860c2d6ed649564e0400291d84270feed29c594770439154246538

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
